/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import modelo.RegistroLibros;

/**
 *
 * @author Erick Gonález
 */
public class Menu extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        jmEstudiante.addActionListener(this);
        jmLibro.addActionListener(this);
        reportesLibros.addActionListener(this);
        registroLibros=new RegistroLibros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmLibro = new javax.swing.JMenuItem();
        jmEstudiante = new javax.swing.JMenuItem();
        jmReporteLibros = new javax.swing.JMenu();
        reportesLibros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Registrar");

        jmLibro.setText("Libro");
        jMenu1.add(jmLibro);

        jmEstudiante.setText("Estudiante");
        jMenu1.add(jmEstudiante);

        jMenuBar1.add(jMenu1);

        jmReporteLibros.setText("Reportes");

        reportesLibros.setText("Libros");
        jmReporteLibros.add(reportesLibros);

        jMenuBar1.add(jmReporteLibros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    private RegistroLibros registroLibros;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmEstudiante;
    private javax.swing.JMenuItem jmLibro;
    private javax.swing.JMenu jmReporteLibros;
    private javax.swing.JMenuItem reportesLibros;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==jmLibro){
            GuiLibro guiLibro =new GuiLibro();
            guiLibro.init(registroLibros);
            guiLibro.setVisible(true);
        }
        if(e.getSource()==jmEstudiante){
            new GuiEstudiante().setVisible(true);
        }
        if(e.getSource()==reportesLibros){
            GuiReporteLibro reporte= new GuiReporteLibro();
            reporte.init(registroLibros);
            reporte.setVisible(true);
        }
    }
}
