/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Libro;

/**
 *
 * @author usuario
 */
public class PanelDatosLibro extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatosLibro
     */
    public PanelDatosLibro() {
        initComponents();
    }
    public Libro getLibro(){
        Libro libro =new Libro(jtISBN.getText(),jtTitulo.getText(),jtAutor.getText());
        return libro;
    }
    
    public boolean verificarDatos(){
        boolean estado=false;
        if(!jtISBN.getText().equals("") && !jtAutor.getText().equals("") && !jtTitulo.getText().equals("")){
            estado=true;
        }
        return estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlISBn = new javax.swing.JLabel();
        jtISBN = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jlAutor = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jtAutor = new javax.swing.JTextField();

        jlISBn.setFont(new java.awt.Font("Trebuchet MS", 3, 15)); // NOI18N
        jlISBn.setText("ISBN:");

        jlTitulo.setText("Titulo:");

        jlAutor.setText("Autor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlISBn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlTitulo)
                    .addComponent(jlAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jtAutor))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlISBn)
                    .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo)
                    .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAutor)
                    .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlISBn;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtISBN;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables
}
